# Setup
title: Surprise
tagline: 'A Python scikit for recommender systems.'
description: 'A simple Python library for building and testing recommender systems.'
sidebar_desc: 'A Python scikit for recommender systems.'
url: http://surpriselib.com
baseurl:

author:
  name: Nicolas Hug
  github: https://github.com/nicolashug
  perso: http://nicolas-hug.com

# Custom vars
version: 1.0.0
docs_url: 'http://surprise.readthedocs.io'
github:
  repo: 'https://github.com/NicolasHug/Surprise'

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
